export const theme = {
  auto: 'auto',
  as: {
    h: 'header',
    m: 'main',
    f: 'footer',
    s: 'section',
    d: 'div',
  },
  display: {
    none: 'none',
    b: 'block',
    f: 'flex',
    g: 'grid',
    ib: 'inline-block',
    if: 'inline-flex',
    ig: 'inline-grid',
  },
  position: {
    l: 'left',
    c: 'center',
    r: 'right',
    a: 'auto',
  },
  colors: {
    text: '#595a5a',
    textLight: '#a6a6a6',
    title: '#292d2d',
    white: '#fff',
    bgSection: '#292d2d',
    bgCard: '#f4d644',
    accent: '#f4d644',
    hover: '#8c52ff',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256, 320, 480, 512, 768, 1024],
  fonts: {
    body: 'roboto, sans-serif',
    heading: 'roboto, sans-serif',
    monospace: 'roboto, monospace',
  },
  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    l: '24px',
    xl: '32px',
    xxl: '64px',
    xxxl: '128px',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    normal: '4px',
    big: '12px',
    round: '50%',
  },
  shadows: {
    card: '1px 1px 4px 0px rgba(102, 102, 130, 1)',
  },
};
